### ISSUE TITLE
impoty modules from python 2.7 fail to load

### ISSUE THREAD

**Issue by Salmon-Bard** [EliasKotlyar/Yowsup-Restful#1]
Hi nice project and certainly deserve more attention from contributors.

I can not get the script to run. I do not know how you get a python3 "run.py" script to run (as you indicate in the project) with imports from python 2.7 Yowsup libraries and others.

I can get Yowsup CLI to work and all installed successfully.
Your assistance is most appreciated.

**Comment by EliasKotlyar** [comment]
Hello 

I havent tested it on Python 2.7 yet. Can you please provide more details,where exactly it fails? You should run it by "python run.py <username> <password>"

**Comment by Salmon-Bard** [comment]
I have both python 3.4 and 2.7 installed (ubuntu 14.04) and all dependencies required for Yowsup. 
Yowsup examples and CLI runs without any problem. Yowsup itself is python 2.7 as I know.

I'm testing it with python3 according to the instructions:
```python3 run.py <user> <password>```
And this through an import error:
```
  File "run.py", line 1, in <module>
    from yowsuprestful.stack import QueueStack
  File "/test/Yowsup-Restful-master/yowsuprestful/stack.py", line 4, in <module>
    from yowsup.layers.network import YowNetworkLayer
ImportError: No module named 'yowsup'
```

**Comment by EliasKotlyar** [comment]
Install the yowsup Module trough Pip3:

pip3 install git+https://github.com/tgalal/yowsup@v2.3.84

Yowsup can be installed on Python3 or Python2.

**Comment by Salmon-Bard** [comment]
Thanks for the clarification. Now all is working great :)

If I may ask: In your code you have created a place holder for supporting sending images from URLs and encoded images ....are there any plans to add support for audio and video upload? also can the API handle sending to Whatsapp groups.
 
Thanks again for your effort and I wish a had good python skills to contribute to this project. Maybe sometime in the future!

**Comment by EliasKotlyar** [comment]
>are there any plans to add support for audio and video upload?
>can the API handle sending to Whatsapp groups?
Not yet,i havent seen a code for doing any of this tasks in the core of the yowsup2 library. As soon i see some example code which have this functions,i could include this functionality.
